[package]
name = "codebook-lsp"
version = "0.1.15"
edition = "2021"

[dependencies]
streaming-iterator = "0.1.9"
tower-lsp = "0.20.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fs2 = "0.4"
tokio = { version = "1", features = ["full"] }
env_logger = "0.11.6"
log = "0.4.22"
codebook = { path = "../codebook" }
codebook_config = { path = "../codebook-config" }
clap = { version = "4.5.26", features = ["derive"] }
lru = "0.13"


[build-dependencies]
cc = "1.0"

[dev-dependencies]
tempfile = "3"
